# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/vsts/pipelines/apps/windows/dot-net

pool:
  vmImage: 'VS2017-Win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- task: UseNode@1
  inputs:
    version: '8.11.3'

- powershell: .\scripts\build.ps1 -configuration $(buildConfiguration) 
  displayName: 'scripts\build.ps1'

- powershell: |
   npm run build:test
  displayName: 'npm run build:test'
  
- task: VSTest@2
  inputs:
    testAssemblyVer2: |
     **\*Tests.js
     !**\node_modules\**\*.js
    runSettingsFile: '$(System.DefaultWorkingDirectory)\RunSettings.xml'
    pathtoCustomTestAdapters: '$(System.DefaultWorkingDirectory)\artifacts\Release\net451'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    runTestsInIsolation: true
    testRunTitle: 'JavaScript Unit Tests'
  displayName: 'JavaScript Unit Tests'
  
- task: VSTest@2
  inputs:
    testAssemblyVer2: |
     **\*UnitTests\**\*.dll
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    testRunTitle: 'C# Unit Tests'
  displayName: 'C# Unit Tests'
  
- task: VSTest@2
  inputs:
    testAssemblyVer2: |
     **\*AcceptanceTests\**\*.dll
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    testRunTitle: 'Acceptance Tests'
  displayName: 'Acceptance Tests'
